var desktopStylesLoaded = false;
            function loadDesktopCSS() {
                if (!desktopStylesLoaded) {
                    if (window.innerWidth >= 600) {
                        for (var i = 0, desktopStyles = document.querySelectorAll('head > link[href*="css"][media="screen and (min-width:37.5em)"]'); i < desktopStyles.length; i++) {
                            desktopStyles[i].removeAttribute("disabled");
                        }
                        desktopStylesLoaded = true;
                    }
                }
            }
            loadDesktopCSS();
            window.addEventListener("resize", loadDesktopCSS);

            const supportsContainerQueries = "container" in document.documentElement.style;
            if (!supportsContainerQueries) {
                fetch(document.querySelector('head > link[data-type="cq"]').getAttribute("href")).then((data) => {
                    data.text().then((css) => {
                        const styleElement = document.createElement("style");
                        styleElement.type = "text/css";
                        document.head.appendChild(styleElement);
                        styleElement.appendChild(document.createTextNode(css));
                    });
                });
                // import("https://cdn.skypack.dev/container-query-polyfill");
            }


            !(function () {
                if (0 == document.getElementsByClassName("wnd-cms").length)
                    for (var e = document.getElementsByClassName("c"), s = 0; s < e.length; s++) {
                        var t = e[s].querySelector("div"),
                            l = t.getElementsByClassName("b-text-c");
                        void 0 != l[0] &&
                            t.firstChild == t.lastChild &&
                            "" === l[0].innerText &&
                            (e[s].classList ? e[s].classList.add("column-empty") : (e[s].classList ? e[s].classList.contains("column-empty") : new RegExp("\\bcolumn-empty\\b").test(e[s].className)) && (e[s].className += " column-empty"));
                    }
            })();


            window.checkAndChangeSvgColor = function (c) {
                try {
                    var a = document.getElementById(c);
                    if (a) {
                        c = [
                            ["border", "borderColor"],
                            ["outline", "outlineColor"],
                            ["color", "color"],
                        ];
                        for (var h, b, d, f = [], e = 0, m = c.length; e < m; e++)
                            if (
                                (h = window
                                    .getComputedStyle(a)
                                    [c[e][1]].replace(/\s/g, "")
                                    .match(/^rgb[a]?\(([0-9]{1,3}),([0-9]{1,3}),([0-9]{1,3})/i))
                            ) {
                                b = "";
                                for (var g = 1; 3 >= g; g++) b += ("0" + parseInt(h[g], 10).toString(16)).slice(-2);
                                "0" === b.charAt(0) && ((d = parseInt(b.substr(0, 2), 16)), (d = Math.max(16, d)), (b = d.toString(16) + b.slice(-4)));
                                f.push(c[e][0] + "=" + b);
                            }
                        if (f.length) {
                            var k = a.getAttribute("data-src"),
                                l = k + (0 > k.indexOf("?") ? "?" : "&") + f.join("&");
                            a.src != l && ((a.src = l), (a.outerHTML = a.outerHTML));
                        }
                    }
                } catch (n) {}
            };


            var wnd = wnd || {};
            wnd.$data = {
                image_content_items: {
                    wnd_ThumbnailBlock_1: { id: "wnd_ThumbnailBlock_1", type: "wnd.pc.ThumbnailBlock" },
                    wnd_HeaderSection_header_main_43840627: { id: "wnd_HeaderSection_header_main_43840627", type: "wnd.pc.HeaderSection" },
                    wnd_ImageBlock_815642624: { id: "wnd_ImageBlock_815642624", type: "wnd.pc.ImageBlock" },
                    wnd_Section_default_995104215: { id: "wnd_Section_default_995104215", type: "wnd.pc.Section" },
                    wnd_LogoBlock_53828925: { id: "wnd_LogoBlock_53828925", type: "wnd.pc.LogoBlock" },
                    wnd_FooterSection_footer_911524909: { id: "wnd_FooterSection_footer_911524909", type: "wnd.pc.FooterSection" },
                },
                svg_content_items: { wnd_ImageBlock_815642624: { id: "wnd_ImageBlock_815642624", type: "wnd.pc.ImageBlock" }, wnd_LogoBlock_53828925: { id: "wnd_LogoBlock_53828925", type: "wnd.pc.LogoBlock" } },
                content_items: [],
                project_info: { isMultilanguage: false, isMulticurrency: false, eshop_tax_enabled: "1", country_code: "sk", contact_state: "", eshop_tax_type: "VAT", eshop_discounts: false },
                eshopSettings: { ESHOP_SETTINGS_DISPLAY_PRICE_WITHOUT_VAT: false, ESHOP_SETTINGS_DISPLAY_ADDITIONAL_VAT: false, ESHOP_SETTINGS_DISPLAY_SHIPPING_COST: false },
            };


            wnd.$system = {
                fileSystemType: "aws_s3",
                localFilesPath: "https:\/\/tomaszajac.webnode.sk\/_files\/",
                awsS3FilesPath: "https:\/\/8d25155765.cbaul-cdnwnd.com\/30b15eebe40a3c4f3a30da882de36dd1\/",
                staticFiles: "https:\/\/d1di2lzuh97fh2.cloudfront.net\/files",
                isCms: false,
                staticCDNServers: ["https:\/\/d1di2lzuh97fh2.cloudfront.net\/"],
                fileUploadAllowExtension: [
                    "jpg",
                    "jpeg",
                    "jfif",
                    "png",
                    "gif",
                    "bmp",
                    "ico",
                    "svg",
                    "webp",
                    "tiff",
                    "pdf",
                    "doc",
                    "docx",
                    "ppt",
                    "pptx",
                    "pps",
                    "ppsx",
                    "odt",
                    "xls",
                    "xlsx",
                    "txt",
                    "rtf",
                    "mp3",
                    "wma",
                    "wav",
                    "ogg",
                    "amr",
                    "flac",
                    "m4a",
                    "3gp",
                    "avi",
                    "wmv",
                    "mov",
                    "mpg",
                    "mkv",
                    "mp4",
                    "mpeg",
                    "m4v",
                    "swf",
                    "gpx",
                    "stl",
                    "csv",
                    "xml",
                    "txt",
                    "dxf",
                    "dwg",
                    "iges",
                    "igs",
                    "step",
                    "stp",
                ],
                maxUserFormFileLimit: 4194304,
                frontendLanguage: "sk",
                backendLanguage: "sk",
                frontendLanguageId: "1",
                page: {
                    id: 200000059,
                    identifier: "obchodne-podmienky",
                    template: {
                        id: 200000007,
                        styles: {
                            typography: "t-02_new",
                            scheme: "cs-gray",
                            additiveColor: "ac-none",
                            acHeadings: true,
                            acSubheadings: false,
                            acIcons: true,
                            acOthers: false,
                            imageStyle: "img-d-n",
                            imageHover: "img-h-z",
                            imageTitle: "img-t-o",
                            buttonStyle: "b-btn-sq",
                            buttonSize: "b-btn-s-l",
                            buttonDecoration: "b-btn-dn",
                            buttonBorders: "b-btn-bw-1",
                            lineStyle: "line-solid",
                            eshopGridItemStyle: "b-e-ds",
                            formStyle: "default",
                            menuType: "",
                            menuStyle: "menu-delimiters-slash",
                            lightboxStyle: "lbox-d",
                            columnSpaces: "c-s-n",
                            sectionWidth: "wnd-w-narrow",
                            sectionSpace: "wnd-s-normal",
                            layoutType: "l-default",
                            layoutDecoration: "l-d-none",
                            background: { default: null },
                            backgroundSettings: { default: "" },
                            typoTitleSizes: "t-t-fs-l",
                            typoTitleWeights: "t-t-fw-m",
                            typoTitleSpacings: "t-t-sp-n",
                            typoTitleDecorations: "t-t-d-n",
                            typoHeadingSizes: "t-h-fs-s",
                            typoHeadingWeights: "t-h-fw-s",
                            typoHeadingSpacings: "t-h-sp-n",
                            typoSubtitleSizes: "t-s-fs-s",
                            typoSubtitleWeights: "t-s-fw-m",
                            typoSubtitleSpacings: "t-s-sp-n",
                            typoSubtitleDecorations: "t-s-d-n",
                            typoParagraphSizes: "t-p-fs-s",
                            typoParagraphWeights: "t-p-fw-l",
                            typoParagraphSpacings: "t-p-sp-n",
                            typoBlockquoteSizes: "t-bq-fs-m",
                            typoBlockquoteWeights: "t-bq-fw-m",
                            typoBlockquoteSpacings: "t-bq-sp-n",
                            typoBlockquoteDecorations: "t-bq-d-l",
                            buttonWeight: "t-btn-fw-l",
                            menuWeight: "t-nav-fw-l",
                            productWeight: "t-pd-fw-s",
                        },
                    },
                    layout: "default",
                    name: "Obchodn\u00e9 podmienky",
                    html_title: "",
                    language: "sk",
                    langId: 1,
                    isHomepage: false,
                    meta_description: "",
                    meta_keywords: "",
                    header_code: "",
                    footer_code: "",
                    styles: { pageBased: { navline: { style: { sectionWidth: "wnd-w-wider", sectionHeight: "wnd-nh-m", sectionPosition: "wnd-na-c" } } } },
                    countFormsEntries: [],
                },
                listingsPrefix: "\/l\/",
                productPrefix: "\/p\/",
                cartPrefix: "\/cart\/",
                checkoutPrefix: "\/checkout\/",
                searchPrefix: "\/search\/",
                isCheckout: false,
                isEshop: false,
                hasBlog: false,
                isProductDetail: false,
                isListingDetail: false,
                listing_page: [],
                hasEshopAnalytics: false,
                gTagId: null,
                gAdsId: null,
                format: {
                    be: {
                        DATE_TIME: {
                            mask: "%d.%m.%Y %H:%M",
                            regexp: "^(((0?[1-9]|[1,2][0-9]|3[0,1])\\.(0?[1-9]|1[0-2])\\.[0-9]{1,4})(( [0-1][0-9]| 2[0-3]):[0-5][0-9])?|(([0-9]{4}(0[1-9]|1[0-2])(0[1-9]|[1,2][0-9]|3[0,1])(0[0-9]|1[0-9]|2[0-3])[0-5][0-9][0-5][0-9])))?$",
                        },
                        DATE: { mask: "%d.%m.%Y", regexp: "^((0?[1-9]|[1,2][0-9]|3[0,1])\\.(0?[1-9]|1[0-2])\\.[0-9]{1,4})$" },
                        CURRENCY: { mask: { point: ",", thousands: " ", decimals: 2, mask: "%s", zerofill: true } },
                    },
                    fe: {
                        DATE_TIME: {
                            mask: "%d.%m.%Y %H:%M",
                            regexp: "^(((0?[1-9]|[1,2][0-9]|3[0,1])\\.(0?[1-9]|1[0-2])\\.[0-9]{1,4})(( [0-1][0-9]| 2[0-3]):[0-5][0-9])?|(([0-9]{4}(0[1-9]|1[0-2])(0[1-9]|[1,2][0-9]|3[0,1])(0[0-9]|1[0-9]|2[0-3])[0-5][0-9][0-5][0-9])))?$",
                        },
                        DATE: { mask: "%d.%m.%Y", regexp: "^((0?[1-9]|[1,2][0-9]|3[0,1])\\.(0?[1-9]|1[0-2])\\.[0-9]{1,4})$" },
                        CURRENCY: { mask: { point: ",", thousands: " ", decimals: 2, mask: "%s", zerofill: true } },
                    },
                },
                e_product: null,
                listing_item: null,
                feReleasedFeatures: {
                    projectFreeBarFixed: false,
                    projectFreeBarFixedButton: true,
                    projectFreeBarFixedButtonDark: false,
                    projectFreeBarV4: false,
                    siteFulltextSearch: true,
                    eshopPriceDisplaySettings: true,
                    eshopUnitPrices: true,
                    dualCurrency: false,
                    HeurekaSatisfactionSurvey: false,
                    useOnlyDefaultFreeBar: true,
                },
                labels: {
                    "dualCurrency.fixedRate": "",
                    "invoicesGenerator.W2EshopInvoice.alreadyPayed": "Nepla\u0165te! - Uhraden\u00e9",
                    "invoicesGenerator.W2EshopInvoice.amount": "Mno\u017estvo:",
                    "invoicesGenerator.W2EshopInvoice.contactInfo": "Kontaktn\u00e9 inform\u00e1cie:",
                    "invoicesGenerator.W2EshopInvoice.couponCode": "K\u00f3d kup\u00f3nu:",
                    "invoicesGenerator.W2EshopInvoice.customer": "Z\u00e1kazn\u00edk:",
                    "invoicesGenerator.W2EshopInvoice.dateOfIssue": "D\u00e1tum vystavenia:",
                    "invoicesGenerator.W2EshopInvoice.dateOfTaxableSupply": "D\u00e1tum uskuto\u010dnenia plnenia",
                    "invoicesGenerator.W2EshopInvoice.dic": "I\u010c DPH:",
                    "invoicesGenerator.W2EshopInvoice.discount": "Z\u013eava",
                    "invoicesGenerator.W2EshopInvoice.dueDate": "D\u00e1tum splatnosti:",
                    "invoicesGenerator.W2EshopInvoice.email": "E-mail:",
                    "invoicesGenerator.W2EshopInvoice.filenamePrefix": "Fakt\u00fara-",
                    "invoicesGenerator.W2EshopInvoice.fiscalCode": "Da\u0148ov\u00fd k\u00f3d:",
                    "invoicesGenerator.W2EshopInvoice.freeShipping": "Doprava zdarma",
                    "invoicesGenerator.W2EshopInvoice.ic": "I\u010cO:",
                    "invoicesGenerator.W2EshopInvoice.invoiceNo": "\u010c\u00edslo fakt\u00fary",
                    "invoicesGenerator.W2EshopInvoice.invoiceNoTaxed": "Fakt\u00fara - Da\u0148ov\u00fd doklad \u010d\u00edslo",
                    "invoicesGenerator.W2EshopInvoice.notVatPayers": "Nie som platite\u013e DPH",
                    "invoicesGenerator.W2EshopInvoice.orderNo": "\u010c\u00edslo objedn\u00e1vky:",
                    "invoicesGenerator.W2EshopInvoice.paymentPrice": "Cena platobnej met\u00f3dy:",
                    "invoicesGenerator.W2EshopInvoice.pec": "PEC:",
                    "invoicesGenerator.W2EshopInvoice.phone": "Telef\u00f3n:",
                    "invoicesGenerator.W2EshopInvoice.priceExTax": "Cena bez dane:",
                    "invoicesGenerator.W2EshopInvoice.priceIncludingTax": "Cena vr\u00e1tane dane:",
                    "invoicesGenerator.W2EshopInvoice.product": "Produkt:",
                    "invoicesGenerator.W2EshopInvoice.productNr": "\u010c\u00edslo produktu:",
                    "invoicesGenerator.W2EshopInvoice.recipientCode": "K\u00f3d pr\u00edjemcu:",
                    "invoicesGenerator.W2EshopInvoice.shippingAddress": "Doru\u010dovacia adresa:",
                    "invoicesGenerator.W2EshopInvoice.shippingPrice": "Cena dopravy:",
                    "invoicesGenerator.W2EshopInvoice.subtotal": "Medzis\u00fa\u010det:",
                    "invoicesGenerator.W2EshopInvoice.sum": "Celkov\u00e1 cena:",
                    "invoicesGenerator.W2EshopInvoice.supplier": "Dod\u00e1vate\u013e",
                    "invoicesGenerator.W2EshopInvoice.tax": "Da\u0148:",
                    "invoicesGenerator.W2EshopInvoice.total": "Celkom:",
                    "invoicesGenerator.W2EshopInvoice.web": "Web:",
                    "wnd.es.CheckoutShippingService.correiosDeliveryWithSpecialConditions":
                        "CEP de destino est\u00e1 sujeito a condi\u00e7\u00f5es especiais de entrega pela ECT e ser\u00e1 realizada com o acr\u00e9scimo de at\u00e9 7 (sete) dias \u00fateis ao prazo regular.",
                    "wnd.es.CheckoutShippingService.correiosWithoutHomeDelivery":
                        "CEP de destino est\u00e1 temporariamente sem entrega domiciliar. A entrega ser\u00e1 efetuada na ag\u00eancia indicada no Aviso de Chegada que ser\u00e1 entregue no endere\u00e7o do destinat\u00e1rio",
                    "wnd.es.ProductEdit.unit.cm": "cm",
                    "wnd.es.ProductEdit.unit.floz": "fl oz",
                    "wnd.es.ProductEdit.unit.ft": "ft",
                    "wnd.es.ProductEdit.unit.ft2": "ft\u00b2",
                    "wnd.es.ProductEdit.unit.g": "g",
                    "wnd.es.ProductEdit.unit.gal": "gal",
                    "wnd.es.ProductEdit.unit.in": "in",
                    "wnd.es.ProductEdit.unit.inventoryQuantity": "ks",
                    "wnd.es.ProductEdit.unit.inventorySize": "cm",
                    "wnd.es.ProductEdit.unit.inventorySize.cm": "cm",
                    "wnd.es.ProductEdit.unit.inventorySize.inch": "inch",
                    "wnd.es.ProductEdit.unit.inventoryWeight": "kg",
                    "wnd.es.ProductEdit.unit.inventoryWeight.kg": "kg",
                    "wnd.es.ProductEdit.unit.inventoryWeight.lb": "lb",
                    "wnd.es.ProductEdit.unit.l": "l",
                    "wnd.es.ProductEdit.unit.m": "m",
                    "wnd.es.ProductEdit.unit.m2": "m\u00b2",
                    "wnd.es.ProductEdit.unit.m3": "m\u00b3",
                    "wnd.es.ProductEdit.unit.mg": "mg",
                    "wnd.es.ProductEdit.unit.ml": "ml",
                    "wnd.es.ProductEdit.unit.mm": "mm",
                    "wnd.es.ProductEdit.unit.oz": "oz",
                    "wnd.es.ProductEdit.unit.pcs": "ks",
                    "wnd.es.ProductEdit.unit.pt": "pt",
                    "wnd.es.ProductEdit.unit.qt": "qt",
                    "wnd.es.ProductEdit.unit.yd": "yd",
                    "wnd.es.ProductList.inventory.outOfStock": "Vypredan\u00e9",
                    "wnd.fe.CheckoutSelectMethodKlarnaPlaygroundItem": "{name} testovac\u00ed \u00fa\u010det",
                    "wnd.fe.CheckoutSelectMethodZasilkovnaItem.change": "Zmeni\u0165 v\u00fddajn\u00e9 miesto",
                    "wnd.fe.CheckoutSelectMethodZasilkovnaItem.choose": "Vyberte si v\u00fddajn\u00e9 miesto",
                    "wnd.fe.CheckoutSelectMethodZasilkovnaItem.error": "Vyberte si pros\u00edm v\u00fddajn\u00e9 miesto",
                    "wnd.fe.CheckoutZipField.brInvalid": "Zadejte pros\u00edm platn\u00e9 PS\u010c ve form\u00e1tu XXXXX-XXX",
                    "wnd.fe.CookieBar.message":
                        "Tieto str\u00e1nky pou\u017e\u00edvaj\u00fa cookies k anal\u00fdze n\u00e1v\u0161tevnosti a bezpe\u010dnej prev\u00e1dzke str\u00e1nok. Pou\u017e\u00edvan\u00edm str\u00e1nok vyjadrujete s\u00fahlas s na\u0161imi pravidlami pre ochranu s\u00fakromia.",
                    "wnd.fe.FeFooter.createWebsite": "Vytvorte si webov\u00e9 str\u00e1nky zdarma!",
                    "wnd.fe.FormManager.error.file.notAllowedExtension": "S\u00fabory s pr\u00edponou \u0022{EXTENSION}\u0022 nie je mo\u017en\u00e9 nahra\u0165.",
                    "wnd.fe.FormManager.error.file.required": "Vyberte pros\u00edm s\u00fabor pre nahranie.",
                    "wnd.fe.FormManager.error.file.sizeExceeded": "Maxim\u00e1lna ve\u013ekos\u0165 nahr\u00e1van\u00e9ho s\u00faboru je {SIZE} MB.",
                    "wnd.fe.FormManager.error.userChangePassword": "Hesl\u00e1 sa nezhoduj\u00fa",
                    "wnd.fe.FormManager.error.userLogin.inactiveAccount": "Va\u0161a registr\u00e1cia e\u0161te nebola schv\u00e1len\u00e1, nem\u00f4\u017eete sa prihl\u00e1si\u0165!",
                    "wnd.fe.FormManager.error.userLogin.invalidLogin": "Neplatn\u00e9 pou\u017e\u00edvate\u013esk\u00e9 meno alebo heslo!",
                    "wnd.fe.FreeBarBlock.buttonText": "Vytvori\u0165 str\u00e1nky",
                    "wnd.fe.FreeBarBlock.longText": "T\u00e1to str\u00e1nka bola vytvoren\u00e1 pomocou slu\u017eby Webnode. \u003Cstrong\u003EVytvorte si vlastn\u00fd web\u003C\/strong\u003E zdarma e\u0161te dnes!",
                    "wnd.fe.ListingData.shortMonthName.Apr": "Apr",
                    "wnd.fe.ListingData.shortMonthName.Aug": "Aug",
                    "wnd.fe.ListingData.shortMonthName.Dec": "Dec",
                    "wnd.fe.ListingData.shortMonthName.Feb": "Feb",
                    "wnd.fe.ListingData.shortMonthName.Jan": "Jan",
                    "wnd.fe.ListingData.shortMonthName.Jul": "J\u00fal",
                    "wnd.fe.ListingData.shortMonthName.Jun": "J\u00fan",
                    "wnd.fe.ListingData.shortMonthName.Mar": "Mar",
                    "wnd.fe.ListingData.shortMonthName.May": "M\u00e1j",
                    "wnd.fe.ListingData.shortMonthName.Nov": "Nov",
                    "wnd.fe.ListingData.shortMonthName.Oct": "Okt",
                    "wnd.fe.ListingData.shortMonthName.Sep": "Sep",
                    "wnd.fe.ShoppingCartManager.count.between2And4": "{COUNT} polo\u017eky",
                    "wnd.fe.ShoppingCartManager.count.moreThan5": "{COUNT} polo\u017eiek",
                    "wnd.fe.ShoppingCartManager.count.one": "{COUNT} polo\u017eka",
                    "wnd.fe.ShoppingCartTable.label.itemsInStock": "Pouze {COUNT} ks k dispozici skladem",
                    "wnd.fe.ShoppingCartTable.label.itemsInStock.between2And4": "Len {COUNT} ks k dispoz\u00edcii na sklade",
                    "wnd.fe.ShoppingCartTable.label.itemsInStock.moreThan5": "Len {COUNT} ks k dispoz\u00edcii na sklade",
                    "wnd.fe.ShoppingCartTable.label.itemsInStock.one": "Len {COUNT} ks k dispoz\u00edcii na sklade",
                    "wnd.fe.ShoppingCartTable.label.outOfStock": "Vypredan\u00e9",
                    "wnd.fe.UserBar.logOut": "Odhl\u00e1si\u0165",
                    "wnd.pc.BlogDetailPageZone.next": "Nov\u0161ie \u010dl\u00e1nky",
                    "wnd.pc.BlogDetailPageZone.previous": "Star\u0161ie \u010dl\u00e1nky",
                    "wnd.pc.ContactInfoBlock.placeholder.infoMail": "Napr. kontakt@example.com",
                    "wnd.pc.ContactInfoBlock.placeholder.infoPhone": "Napr. +421 123 456 789",
                    "wnd.pc.ContactInfoBlock.placeholder.infoText": "Napr. M\u00e1me otvoren\u00e9 denne od 8:00 do 16:00",
                    "wnd.pc.CookieBar.button.advancedClose": "Zavrie\u0165",
                    "wnd.pc.CookieBar.button.advancedOpen": "Otvori\u0165 pokro\u010dil\u00e9 nastavenia",
                    "wnd.pc.CookieBar.button.advancedSave": "Ulo\u017ei\u0165",
                    "wnd.pc.CookieBar.link.disclosure": "Disclosure",
                    "wnd.pc.CookieBar.title.advanced": "Pokro\u010dil\u00e9 nastavenia",
                    "wnd.pc.CookieBar.title.option.functional": "Funk\u010dn\u00e9 cookies",
                    "wnd.pc.CookieBar.title.option.marketing": "Marketingov\u00e9 cookies",
                    "wnd.pc.CookieBar.title.option.necessary": "Nevyhnutn\u00e9 kr\u00e1tkodob\u00e9 cookies",
                    "wnd.pc.CookieBar.title.option.performance": "V\u00fdkonnostn\u00e9 cookies",
                    "wnd.pc.CookieBarReopenBlock.text": "Cookies",
                    "wnd.pc.FileBlock.download": "STIAHNU\u0164",
                    "wnd.pc.FormBlock.action.defaultMessage.text": "Formul\u00e1r bol \u00faspe\u0161ne odoslan\u00fd.",
                    "wnd.pc.FormBlock.action.defaultMessage.title": "\u010eakujeme!",
                    "wnd.pc.FormBlock.action.invisibleCaptchaInfoText":
                        "T\u00e1to str\u00e1nka je chr\u00e1nen\u00e1 slu\u017ebou reCAPTCHA, na ktor\u00fa sa vz\u0165ahuj\u00fa \u003Clink1\u003EZ\u00e1sady ochrany osobn\u00fdch \u00fadajov\u003C\/link1\u003E a \u003Clink2\u003EZmluvn\u00e9 podmienky\u003C\/link2\u003E spolo\u010dnosti Google.",
                    "wnd.pc.FormBlock.action.submitBlockedDisabledBecauseSiteSecurity": "Formul\u00e1r nie je mo\u017en\u00e9 odosla\u0165 (vlastn\u00edk str\u00e1nok zablokoval va\u0161u lokalitu).",
                    "wnd.pc.FormBlock.mail.value.no": "Nie",
                    "wnd.pc.FormBlock.mail.value.yes": "\u00c1no",
                    "wnd.pc.FreeBarBlock.longText": "wnd.pc.FreeBarBlock.longText",
                    "wnd.pc.FreeBarBlock.text": "Vytvoren\u00e9 slu\u017ebou",
                    "wnd.pc.ListingDetailPageZone.next": "Nasleduj\u00face",
                    "wnd.pc.ListingDetailPageZone.previous": "Predch\u00e1dzaj\u00face",
                    "wnd.pc.ListingItemCopy.namePrefix": "K\u00f3pia -",
                    "wnd.pc.Option.defaultText": "\u010eal\u0161ia mo\u017enos\u0165",
                    "wnd.pc.PageCopy.namePrefix": "K\u00f3pia -",
                    "wnd.pc.PhotoGalleryBlock.placeholder.text": "T\u00e1to fotogal\u00e9ria neobsahuje \u017eiadne obr\u00e1zky.",
                    "wnd.pc.PhotoGalleryBlock.placeholder.title": "Fotogal\u00e9ria",
                    "wnd.pc.ProductAddToCartBlock.addToCart": "Do ko\u0161\u00edka",
                    "wnd.pc.ProductGalleryBlock.placeholder.text": "V tejto gal\u00e9rii nie s\u00fa \u017eiadne produkty.",
                    "wnd.pc.ProductGalleryBlock.placeholder.title": "Gal\u00e9ria produktu",
                    "wnd.pc.ProductItem.button.viewDetail": "Produktov\u00e1 str\u00e1nka",
                    "wnd.pc.ProductOptionGroupBlock.notSelected": "Nem\u00e1te vybran\u00e9",
                    "wnd.pc.ProductOutOfStockBlock.label": "Vypredan\u00e9",
                    "wnd.pc.ProductPriceBlock.prefixText": "Cena od ",
                    "wnd.pc.ProductPriceBlock.suffixText": "",
                    "wnd.pc.ProductPriceExcludingVATBlock.USContent": "cena bez DPH",
                    "wnd.pc.ProductPriceExcludingVATBlock.content": "cena vr\u00e1tane DPH",
                    "wnd.pc.ProductShippingInformationBlock.content": "nezah\u0155\u0148a cenu dopravy",
                    "wnd.pc.ProductVATInformationBlock.content": "bez DPH {PRICE}",
                    "wnd.pc.ProductsZone.label.collections": "Kateg\u00f3rie",
                    "wnd.pc.ProductsZone.placeholder.noProductsInCategory": "T\u00e1to kateg\u00f3ria je pr\u00e1zdna. Pridajte do nej produkty, alebo vyberte in\u00fa kateg\u00f3riu.",
                    "wnd.pc.ProductsZone.placeholder.text": "V e-shope zatia\u013e nem\u00e1te \u017eiadny produkt. Kliknite na \u0022Prida\u0165 produkt\u0022.",
                    "wnd.pc.ProductsZone.placeholder.title": "Produkty",
                    "wnd.pc.ProductsZoneModel.label.allCollections": "V\u0161etky produkty",
                    "wnd.pc.SearchBlock.allListingItems": "V\u0161etky \u010dl\u00e1nky",
                    "wnd.pc.SearchBlock.allPages": "V\u0161etky str\u00e1nky",
                    "wnd.pc.SearchBlock.allProducts": "V\u0161etky produkty",
                    "wnd.pc.SearchBlock.allResults": "Zobrazi\u0165 v\u0161etky v\u00fdsledky",
                    "wnd.pc.SearchBlock.iconText": "H\u013eada\u0165",
                    "wnd.pc.SearchBlock.inputPlaceholder": "\u010co h\u013ead\u00e1te?",
                    "wnd.pc.SearchBlock.matchInListingItemIdentifier": "\u010cl\u00e1nok s v\u00fdrazom \u0022{IDENTIFIER}\u0022 v URL",
                    "wnd.pc.SearchBlock.matchInPageIdentifier": "Str\u00e1nka s v\u00fdrazem \u0022{IDENTIFIER}\u0022 v URL",
                    "wnd.pc.SearchBlock.noResults": "Ni\u010d sme nena\u0161li",
                    "wnd.pc.SearchBlock.requestError": "Chyba: Nie je mo\u017en\u00e9 zobrazi\u0165 \u010fal\u0161ie v\u00fdsledky, sk\u00faste pros\u00edm obnovi\u0165 str\u00e1nku, alebo \u003Clink1\u003Ekliknite sem\u003C\/link1\u003E",
                    "wnd.pc.SearchResultsZone.emptyResult": "K tomuto vyh\u013ead\u00e1vaniu sme ni\u010d nena\u0161li. Sk\u00faste pros\u00edm pou\u017ei\u0165 in\u00fd v\u00fdraz.",
                    "wnd.pc.SearchResultsZone.foundProducts": "N\u00e1jden\u00e9 produkty:",
                    "wnd.pc.SearchResultsZone.listingItemsTitle": "\u010cl\u00e1nky",
                    "wnd.pc.SearchResultsZone.pagesTitle": "Str\u00e1nky",
                    "wnd.pc.SearchResultsZone.productsTitle": "Produkty",
                    "wnd.pc.SearchResultsZone.title": "V\u00fdsledky h\u013eadania:",
                    "wnd.pc.SectionMsg.name.eshopCategories": "Kateg\u00f3rie",
                    "wnd.pc.ShoppingCartTable.label.checkout": "Objedna\u0165",
                    "wnd.pc.ShoppingCartTable.label.checkoutDisabled": "Objedn\u00e1vku nie je mo\u017en\u00e9 dokon\u010di\u0165 (nie s\u00fa dostupn\u00e9 \u017eiadne doru\u010dovacie alebo platobn\u00e9 met\u00f3dy)",
                    "wnd.pc.ShoppingCartTable.label.checkoutDisabledBecauseSiteSecurity": "Objedn\u00e1vku nie je mo\u017en\u00e9 dokon\u010di\u0165 (vlastn\u00edk e-shopu zablokoval va\u0161u lokalitu).",
                    "wnd.pc.ShoppingCartTable.label.continue": "Pokra\u010dova\u0165 v n\u00e1kupe",
                    "wnd.pc.ShoppingCartTable.label.delete": "Zmaza\u0165",
                    "wnd.pc.ShoppingCartTable.label.item": "Produkt",
                    "wnd.pc.ShoppingCartTable.label.price": "Cena",
                    "wnd.pc.ShoppingCartTable.label.quantity": "Mno\u017estvo",
                    "wnd.pc.ShoppingCartTable.label.sum": "Celkom",
                    "wnd.pc.ShoppingCartTable.label.totalPrice": "Celkom",
                    "wnd.pc.ShoppingCartTable.placeholder.text": "Vy to ale m\u00f4\u017eete zmeni\u0165! Vyberte si z na\u0161ej ponuky.",
                    "wnd.pc.ShoppingCartTable.placeholder.title": "V\u00e1\u0161 ko\u0161\u00edk je zatia\u013e pr\u00e1zdny",
                    "wnd.pc.ShoppingCartTotalPriceExcludingVATBlock.label": "bez DPH",
                    "wnd.pc.ShoppingCartTotalPriceInformationBlock.label": "Nezah\u0155\u0148a cenu dopravy",
                    "wnd.pc.ShoppingCartTotalPriceWithVATBlock.label": "vr\u00e1tane DPH",
                    "wnd.pc.ShoppingCartTotalVATBlock.label": "DPH {RATE} %",
                    "wnd.pc.SystemFooterBlock.poweredByWebnode": "Vytvoren\u00e9 slu\u017ebou {START_LINK}Webnode{END_LINK}",
                    "wnd.pc.UserBar.logoutText": "Odhl\u00e1si\u0165 sa",
                    "wnd.pc.UserChangePasswordFormBlock.invalidRecoveryUrl":
                        "Platnos\u0165 odkazu, ktor\u00fd v\u00e1m umo\u017en\u00ed zmeni\u0165 heslo, u\u017e vypr\u0161ala. Ak chcete posla\u0165 nov\u00fd odkaz, pokra\u010dujte pros\u00edm na str\u00e1nku {START_LINK}Zabudnut\u00e9 heslo{END_LINK}",
                    "wnd.pc.UserRecoveryFormBlock.action.defaultMessage.text":
                        "Na va\u0161u e-mailov\u00fa adresu sme poslali spr\u00e1vu s odkazom, ktor\u00fd v\u00e1m umo\u017en\u00ed zmeni\u0165 heslo. Ak v\u00e1m spr\u00e1va nepri\u0161la, skontrolujte pros\u00edm nevy\u017eiadan\u00fa po\u0161tu.",
                    "wnd.pc.UserRecoveryFormBlock.action.defaultMessage.title": "Po\u017eiadavka na zmenu hesla bola odoslan\u00e1.",
                    "wnd.pc.UserRegistrationFormBlock.action.defaultMessage.text":
                        "Va\u0161a registr\u00e1cia teraz \u010dak\u00e1 na schv\u00e1lenie a nie je mo\u017en\u00e9 sa na str\u00e1nkach prihl\u00e1si\u0165. Akon\u00e1hle v\u00e1m registr\u00e1ciu schv\u00e1lime, po\u0161leme v\u00e1m e-mailov\u00fa spr\u00e1vu.",
                    "wnd.pc.UserRegistrationFormBlock.action.defaultMessage.title": "\u010eakujeme za registr\u00e1ciu na na\u0161ich str\u00e1nkach.",
                    "wnd.pc.UserRegistrationFormBlock.action.successfulRegistrationMessage.text":
                        "Va\u0161a registr\u00e1cia prebehla v poriadku a vy sa teraz m\u00f4\u017eete prihl\u00e1si\u0165 do zamknut\u00fdch str\u00e1nok tohto webu.",
                    "wnd.pm.AddNewPagePattern.onlineStore": "Internetov\u00fd obchod",
                    "wnd.ps.CookieBarSettingsForm.default.advancedMainText":
                        "Tu m\u00f4\u017eete upravi\u0165 svoje preferencie oh\u013eadom cookies. Nasleduj\u00face kateg\u00f3rie m\u00f4\u017eete povoli\u0165 \u010di zak\u00e1za\u0165 a svoj v\u00fdber ulo\u017ei\u0165.",
                    "wnd.ps.CookieBarSettingsForm.default.captionAcceptAll": "Prija\u0165 v\u0161etko",
                    "wnd.ps.CookieBarSettingsForm.default.captionAcceptNecessary": "Prija\u0165 nevyhnutn\u00e9",
                    "wnd.ps.CookieBarSettingsForm.default.mainText":
                        "Pou\u017e\u00edvame cookies, aby sme zaistili spr\u00e1vne fungovanie a bezpe\u010dnos\u0165 na\u0161ich str\u00e1nok. T\u00fdm v\u00e1m m\u00f4\u017eeme poskytn\u00fa\u0165 t\u00fa najlep\u0161iu sk\u00fasenos\u0165 z ich n\u00e1v\u0161tevy.",
                    "wnd.template.checkoutSubTitle": "Choose your billing frequency and preferred payment method",
                },
                fontSubset: null,
            };


            wnd.trackerConfig = {
                events: {
                    error: { name: "Error" },
                    publish: { name: "Publish page" },
                    open_premium_popup: { name: "Open premium popup" },
                    upgrade_your_plan: { name: "Upgrade your plan" },
                    ml_lock_page: { name: "Lock access to page" },
                    ml_unlock_page: { name: "Unlock access to page" },
                    ml_start_add_page_member_area: { name: "Start - add page Member Area" },
                    ml_end_add_page_member_area: { name: "End - add page Member Area" },
                    ml_show_activation_popup: { name: "Show activation popup" },
                    ml_activation: { name: "Member Login Activation" },
                    ml_deactivation: { name: "Member Login Deactivation" },
                    ml_enable_require_approval: { name: "Enable approve registration manually" },
                    ml_disable_require_approval: { name: "Disable approve registration manually" },
                    ml_fe_member_registration: { name: "Member Registration on FE" },
                    ml_fe_member_login: { name: "Login Member" },
                    ml_fe_member_recovery: { name: "Sent recovery email" },
                    ml_fe_member_change_password: { name: "Change Password" },
                    undoredo_click_undo: { name: "Undo\/Redo - click Undo" },
                    undoredo_click_redo: { name: "Undo\/Redo - click Redo" },
                    add_page: { name: "Page adding completed" },
                    change_page_order: { name: "Change of page order" },
                    delete_page: { name: "Page deleted" },
                    background_options_change: { name: "Background setting completed" },
                    add_content: { name: "Content adding completed" },
                    delete_content: { name: "Content deleting completed" },
                    change_text: { name: "Editing of text completed" },
                    add_image: { name: "Image adding completed" },
                    add_photo: { name: "Adding photo to galery completed" },
                    change_logo: { name: "Logo changing completed" },
                    open_pages: { name: "Open Pages" },
                    show_page_cms: { name: "Show Page - CMS" },
                    new_section: { name: "New section completed" },
                    delete_section: { name: "Section deleting completed" },
                    add_video: { name: "Video adding completed" },
                    add_maps: { name: "Maps adding completed" },
                    add_button: { name: "Button adding completed" },
                    add_file: { name: "File adding completed" },
                    add_hr: { name: "Horizontal line adding completed" },
                    delete_cell: { name: "Cell deleting completed" },
                    delete_microtemplate: { name: "Microtemplate deleting completed" },
                    add_blog_page: { name: "Blog page adding completed" },
                    new_blog_post: { name: "New blog post created" },
                    new_blog_recent_posts: { name: "Blog recent posts list created" },
                    e_show_products_popup: { name: "Show products popup" },
                    e_show_add_product: { name: "Show add product popup" },
                    e_show_edit_product: { name: "Show edit product popup" },
                    e_show_collections_popup: { name: "Show collections manager popup" },
                    e_show_eshop_settings: { name: "Show eshop settings popup" },
                    e_add_product: { name: "Add product" },
                    e_edit_product: { name: "Edit product" },
                    e_remove_product: { name: "Remove product" },
                    e_bulk_show: { name: "Bulk show products" },
                    e_bulk_hide: { name: "Bulk hide products" },
                    e_bulk_remove: { name: "Bulk remove products" },
                    e_move_product: { name: "Order products" },
                    e_add_collection: { name: "Add collection" },
                    e_rename_collection: { name: "Rename collection" },
                    e_remove_collection: { name: "Remove collection" },
                    e_add_product_to_collection: { name: "Assign product to collection" },
                    e_remove_product_from_collection: { name: "Unassign product from collection" },
                    e_move_collection: { name: "Order collections" },
                    e_add_products_page: { name: "Add products page" },
                    e_add_procucts_section: { name: "Add products list section" },
                    e_add_products_content: { name: "Add products list content block" },
                    e_change_products_zone_style: { name: "Change style in products list" },
                    e_change_products_zone_collection: { name: "Change collection in products list" },
                    e_show_products_zone_collection_filter: { name: "Show collection filter in products list" },
                    e_hide_products_zone_collection_filter: { name: "Hide collection filter in products list" },
                    e_show_product_detail_page: { name: "Show product detail page" },
                    e_add_to_cart: { name: "Add product to cart" },
                    e_remove_from_cart: { name: "Remove product from cart" },
                    e_checkout_step: { name: "From cart to checkout" },
                    e_finish_checkout: { name: "Finish order" },
                    welcome_window_play_video: { name: "Welcome window - play video" },
                    e_import_file: { name: "Eshop - products import - file info" },
                    e_import_upload_time: { name: "Eshop - products import - upload file duration" },
                    e_import_result: { name: "Eshop - products import result" },
                    e_import_error: { name: "Eshop - products import - errors" },
                    e_promo_blogpost: { name: "Eshop promo - blogpost" },
                    e_promo_activate: { name: "Eshop promo - activate" },
                    e_settings_activate: { name: "Online store - activate" },
                    e_promo_hide: { name: "Eshop promo - close" },
                    e_activation_popup_step: { name: "Eshop activation popup - step" },
                    e_activation_popup_activate: { name: "Eshop activation popup - activate" },
                    e_activation_popup_hide: { name: "Eshop activation popup - close" },
                    e_deactivation: { name: "Eshop deactivation" },
                    e_reactivation: { name: "Eshop reactivation" },
                    e_variant_create_first: { name: "Eshop - variants - add first variant" },
                    e_variant_add_option_row: { name: "Eshop - variants - add option row" },
                    e_variant_remove_option_row: { name: "Eshop - variants - remove option row" },
                    e_variant_activate_edit: { name: "Eshop - variants - activate edit" },
                    e_variant_deactivate_edit: { name: "Eshop - variants - deactivate edit" },
                    move_block_popup: { name: "Move block - show popup" },
                    move_block_start: { name: "Move block - start" },
                    publish_window: { name: "Publish window" },
                    welcome_window_video: { name: "Video welcome window" },
                    cookiebar_show: { name: "Cookiebar was shown" },
                    cookiebar_accept_all: { name: "User accepted all cookies" },
                    cookiebar_accept_necessary: { name: "User accepted necessary cookies" },
                },
                data: {
                    user: { u: 0, p: 45683138, lc: "SK", t: "1" },
                    action: { identifier: "", name: "", category: "project", platform: "WND2", version: "2-1549_2-1549" },
                    browser: {
                        url: "https:\/\/tomaszajac.webnode.sk\/obchodne-podmienky\/",
                        ua: "Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/113.0.0.0 Safari\/537.36",
                        referer_url: "https:\/\/tomaszajac.webnode.sk\/kontakt\/",
                        resolution: "",
                        ip: "78.99.32.161",
                    },
                },
                urlPrefix: "https://events.webnode.com/projects/-/events/",
                collection: "PROD",
            };